apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-configmap
data:
  HOST_DB: db-noticias-svc:3306
  USER_DB: root
  PASS_DB: q1w2e3r4
  DATABASE_DB: empresa
---
apiVersion: v1
kind: Service
metadata:
  name: sistema-noticias-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: sistema-noticias
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagens-sistema-noticia-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessao-sistema-noticia-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sistema-noticias
      name: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessao
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 25
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-sistema-noticia-pvc
        - name: sessao
          persistentVolumeClaim: 
            claimName: sessao-sistema-noticia-pvc
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: sistema-noticias-svc
